// tailwind.config.js
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      backgroundImage: {
        parallax:
          'url("https://images.unsplash.com/photo-1533134486753-c833f0ed4866?q=80&w=2370&auto=format&fit=crop")',
      },
    },
  },
  safelist: [
    // flex direction
    "flex-row",
    "flex-row-reverse",
    "flex-col",
    "flex-col-reverse",
    "sm:flex-row",
    "sm:flex-row-reverse",
    "sm:flex-col",
    "sm:flex-col-reverse",
    "md:flex-row",
    "md:flex-row-reverse",
    "md:flex-col",
    "md:flex-col-reverse",
    "lg:flex-row",
    "lg:flex-row-reverse",
    "lg:flex-col",
    "lg:flex-col-reverse",
    "xl:flex-row",
    "xl:flex-row-reverse",
    "xl:flex-col",
    "xl:flex-col-reverse",

    // justify
    "justify-start",
    "justify-center",
    "justify-end",
    "justify-between",
    "justify-around",
    "justify-evenly",
    "sm:justify-start",
    "sm:justify-center",
    "sm:justify-end",
    "sm:justify-between",
    "sm:justify-around",
    "sm:justify-evenly",
    "md:justify-start",
    "md:justify-center",
    "md:justify-end",
    "md:justify-between",
    "md:justify-around",
    "md:justify-evenly",
    "lg:justify-start",
    "lg:justify-center",
    "lg:justify-end",
    "lg:justify-between",
    "lg:justify-around",
    "lg:justify-evenly",
    "xl:justify-start",
    "xl:justify-center",
    "xl:justify-end",
    "xl:justify-between",
    "xl:justify-around",
    "xl:justify-evenly",

    // align
    "items-start",
    "items-center",
    "items-end",
    "items-stretch",
    "items-baseline",
    "sm:items-start",
    "sm:items-center",
    "sm:items-end",
    "sm:items-stretch",
    "sm:items-baseline",
    "md:items-start",
    "md:items-center",
    "md:items-end",
    "md:items-stretch",
    "md:items-baseline",
    "lg:items-start",
    "lg:items-center",
    "lg:items-end",
    "lg:items-stretch",
    "lg:items-baseline",
    "xl:items-start",
    "xl:items-center",
    "xl:items-end",
    "xl:items-stretch",
    "xl:items-baseline",

    // wrap
    "flex-wrap",
    "flex-nowrap",
    "flex-wrap-reverse",
    "sm:flex-wrap",
    "sm:flex-nowrap",
    "sm:flex-wrap-reverse",
    "md:flex-wrap",
    "md:flex-nowrap",
    "md:flex-wrap-reverse",
    "lg:flex-wrap",
    "lg:flex-nowrap",
    "lg:flex-wrap-reverse",
    "xl:flex-wrap",
    "xl:flex-nowrap",
    "xl:flex-wrap-reverse",

    // gap
    "gap-0",
    "gap-1",
    "gap-2",
    "gap-4",
    "gap-6",
    "gap-8",
    "sm:gap-0",
    "sm:gap-1",
    "sm:gap-2",
    "sm:gap-4",
    "sm:gap-6",
    "sm:gap-8",
    "md:gap-0",
    "md:gap-1",
    "md:gap-2",
    "md:gap-4",
    "md:gap-6",
    "md:gap-8",
    "lg:gap-0",
    "lg:gap-1",
    "lg:gap-2",
    "lg:gap-4",
    "lg:gap-6",
    "lg:gap-8",
    "xl:gap-0",
    "xl:gap-1",
    "xl:gap-2",
    "xl:gap-4",
    "xl:gap-6",
    "xl:gap-8",

    // fonts
    "font-heading",
    "font-body"
  ],
} 
