/**
 * UTM Parameters for campaign tracking
 * Standard across all marketing platforms (Google, Facebook, etc.)
 */
export type UTMParameters = {
  utm_source?: string; // Platform: 'facebook', 'google', 'instagram', 'email'
  utm_medium?: string; // Channel type: 'cpc', 'social', 'email', 'organic'
  utm_campaign?: string; // Campaign name: 'valentines_2026', 'summer_sale'
  utm_content?: string; // Ad/content variant: 'hero_cta', 'sidebar_banner'
  utm_term?: string; // Search terms (for paid search)
};

/**
 * Platform-specific click IDs (auto-generated by ad platforms)
 */
export type PlatformClickIDs = {
  gclid?: string; // Google Ads Click ID
  fbclid?: string; // Facebook/Instagram Click ID
  msclkid?: string; // Microsoft Ads Click ID
  ttclid?: string; // TikTok Click ID
};

/**
 * Base GTM event with common properties
 */
export type BaseGTMEvent = UTMParameters &
  PlatformClickIDs & {
    event: string;
    page_path?: string;
    page_title?: string;
    user_id?: string;
    timestamp?: number;
  };

/**
 * Button Click Event
 */
export type ElementClickedEvent = BaseGTMEvent & {
  event: "element_clicked";
  name: string;
  location: string;
  type?:
    | "cta"
    | "navigation"
    | "form"
    | "action"
    | "button"
    | "link"
    | "banner";
};

/**
 * Landing Page View Event
 */
export type ElementViewedEvent = BaseGTMEvent & {
  event: "element_viewed";
  name: string;
  location?: string;
  type: "landing_page" | "section" | "banner" | "form" | "product";
  theme?: "date-night" | "galentines" | "birthday" | "custom";
};

/**
 * Form Submission Event
 */
export type FormSubmitEvent = BaseGTMEvent & {
  event: "form_submit";
  form_name: string;
  form_type: "reservation" | "contact" | "newsletter" | "vip";
  success: boolean;
};

/**
 * Checkout Event
 */
export type CheckoutEvent = BaseGTMEvent & {
  event: "begin_checkout";
  checkout_type: "reservation" | "shop" | "in-store";
  total_amount: number;
  items?: Array<{
    item_name: string;
    item_id: string;
    sku: string;
    price: number;
    quantity: number;
  }>;
};

/**
 * Purchase Event
 */
export type PurchaseEvent = BaseGTMEvent & {
  event: "purchase";
  transaction_id: string;
  value: number;
  currency: string;
  checkout_type: "reservation" | "shop" | "vip";
};

/**
 * Union type of all possible GTM events
 */
export type GTMEvent =
  | ElementClickedEvent
  | ElementViewedEvent
  | FormSubmitEvent
  | CheckoutEvent
  | PurchaseEvent
  | BaseGTMEvent;
