import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/client/Header";
import { CartProvider } from "@/components/client/Cart/CartContext";
import { ModalProvider } from "@/components/client/ModalContext";
import { CartModalProvider } from "@/components/client/CartModalContext";
import { AuthProvider } from "@/components/client/Auth/AuthContext";
import { FavoritesProvider } from "@/components/client/Favorites/FavoritesContext";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <AuthProvider>
          <CartModalProvider>
            <CartProvider>
              <ModalProvider>
                <FavoritesProvider>
                  <Header />
                  {children}
                  <Analytics />
                  <SpeedInsights />
                  <Toaster
                    position="top-right"
                    richColors
                    closeButton
                    expand
                    visibleToasts={3}
                  />
                </FavoritesProvider>
              </ModalProvider>
            </CartProvider>
          </CartModalProvider>
        </AuthProvider>
        <div id="modal-root"></div>
        <div id="cart-modal-root"></div>
      </body>
    </html>
  );
}
