import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/client/Header";
import { CartProvider } from "@/components/client/Cart/CartContext";
import { ModalProvider } from "@/components/client/ModalContext";
import { CartModalProvider } from "@/components/client/CartModalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<html>
      <body>
        <ModalProvider>
          <CartModalProvider>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
          </CartModalProvider>
        </ModalProvider>
        <div id="modal-root"></div>
        <div id="cart-modal-root"></div>
      </body>
</html>

  );
}
